[0m12:30:58.450161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DFB997AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DFB997E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DF869FC90>]}


============================== 12:30:58.466219 | 4aff5ce3-0e27-4cce-9b17-8cdedb6d94a3 ==============================
[0m12:30:58.466219 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:30:58.466219 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Simi Mathew\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select fct_sales_by_month_ytd.sql', 'send_anonymous_usage_stats': 'True'}
[0m12:30:58.466219 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Retail-Sales-Performance-Tracker\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:30:58.466219 [debug] [MainThread]: Command `dbt run` failed at 12:30:58.466219 after 0.10 seconds
[0m12:30:58.466219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DFB9615D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DFB9BFBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023DFB9BE250>]}
[0m12:30:58.466219 [debug] [MainThread]: Flushing usage events
[0m12:30:59.470067 [debug] [MainThread]: An error was encountered while trying to flush usage events
